# server
server:
  port: 8081

spring:
  profiles:
    include:
      - keycloak
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/sms?characterEncoding=utf8&useSSL=false
    username: root
    password: root
    hikari:
      maximum-pool-size: 100
      minimum-idle: 2
      connection-timeout: 5000

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# swagger
swagger:
  enabled: true
  title: 短信服务API接口文档
  description: 短信服务API接口文档
  contact:
    name: 张晓峰
    url: https://leonzhangxf.com
    email: leonzhangxf@gmail.com

# logger
logging:
  level:
    root: info
    org.springframework: info
    com.boxuegu: info
    org.keycloak: debug
  path: /tmp/sms-api-dist

# keycloak 核心配置
keycloak:
  enabled: false
  realm: employee
  auth-server-url: http://127.0.0.1:8080/auth
  ssl-required: none
  resource: sms-api-dist
  cors: true
  bearer-only: true
  autodetect-bearer-only: true
  credentials:
    secret: 8b2deef9-fc4b-46b2-9678-26a9a02f48b4