# server
server:
  port: 8081

# swagger
swagger:
  enabled: true
  title: 接口文档
  description: 接口文档描述
  contact:
    name: 张晓峰
    url: https://leonzhangxf.com
    email: leonzhangxf@gmail.com

# logger
logging:
  level:
    root: info
    org.springframework: info
    com.boxuegu: info
    org.keycloak: debug
  path: /tmp/sms-api-dist

# keycloak 核心配置
keycloak:
  enabled: true
  realm: employee
  auth-server-url: http://127.0.0.1:8080/auth
  ssl-required: none
  resource: sms-api-dist
  cors: true
  bearer-only: true
  autodetect-bearer-only: true
  credentials:
    secret: 8b2deef9-fc4b-46b2-9678-26a9a02f48b4

# keycloak 授权配置
spring:
  profiles:
    include:
      - keycloak

